version: '3'
services:
  selenoid:
    container_name: selenoid
    image: "aerokube/selenoid:1.11.2"
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "$PWD/services/selenoid:/etc/selenoid/" # assumed current dir contains browsers.json
      - "$PWD/services/selenoid/video:/opt/selenoid/video"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=$PWD/services/selenoid/video
  selenoid-ui:
    container_name: selenoid-ui
    image: "aerokube/selenoid-ui:1.10.11"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
  selenoid-video-recorder:
    container_name: selenoid-video-recorder
    image: "selenoid/video-recorder:latest-release"
