---
name: CI/CD
'on':
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Setup docker compose
        run: "docker compose version"

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 7.6.1

      - name: Run application
        run: "make run-application"

      - name: Run tests
        run: "make run-tests"

      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()    # run this step even if previous step failed
        with:
          report_paths: services/tests/build/test-results/runTests/TEST-*.xml    # Path to test results
